# Generated by Django 5.1.4 on 2025-05-20 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Час створення чату')),
                ('announcement', models.ForeignKey(help_text='Оголошення, до якого прив’язаний чат', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='announcements.announcement')),
                ('buyer', models.ForeignKey(help_text='Покупець у чаті', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='Продавець у чаті', on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чати',
                'unique_together': {('announcement', 'buyer', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.TextField(blank=True, help_text='Зашифрований вміст повідомлення', null=True)),
                ('image', models.ImageField(blank=True, help_text='Зображення, прикріплене до повідомлення', null=True, upload_to='chat_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Час відправлення повідомлення')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Час останнього редагування повідомлення', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Чи прочитане повідомлення')),
                ('read_at', models.DateTimeField(blank=True, help_text='Час, коли повідомлення було прочитане', null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Чи було повідомлення відредаговане')),
                ('chat', models.ForeignKey(help_text='Чат, до якого належить повідомлення', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('sender', models.ForeignKey(help_text='Відправник повідомлення', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, help_text='Чи є користувач онлайн')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Час останньої активності користувача')),
                ('user', models.OneToOneField(help_text='Користувач, якому належить цей статус', on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус користувача',
                'verbose_name_plural': 'Статуси користувачів',
            },
        ),
    ]
