# Generated by Django 5.1.4 on 2025-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by_buyer',
            field=models.BooleanField(default=False, help_text='Чи видалив покупець цей чат'),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_seller',
            field=models.BooleanField(default=False, help_text='Чи видалив продавець цей чат'),
        ),
    ]
