# Generated by Django 5.1.4 on 2025-04-10 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_delete_chat'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чати'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'Статус користувача', 'verbose_name_plural': 'Статуси користувачів'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Чи було повідомлення відредаговане'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Час, коли повідомлення було прочитане', null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='announcement',
            field=models.ForeignKey(help_text='Оголошення, до якого прив’язаний чат', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='announcements.announcement'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='buyer',
            field=models.ForeignKey(help_text='Покупець у чаті', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Час створення чату'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='seller',
            field=models.ForeignKey(help_text='Продавець у чаті', on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(help_text='Чат, до якого належить повідомлення', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Час останнього редагування повідомлення', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, help_text='Зашифрований вміст повідомлення', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Зображення, прикріплене до повідомлення', null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Чи прочитане повідомлення'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='Відправник повідомлення', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Час відправлення повідомлення'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Чи є користувач онлайн'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Час останньої активності користувача'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(help_text='Користувач, якому належить цей статус', on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
    ]
