# Generated by Django 5.1.4 on 2025-05-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_deleted_by_buyer_chat_deleted_by_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by_buyer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by_seller',
        ),
    ]
