# Generated by Django 5.1.4 on 2025-05-15 19:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категорія')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'indexes': [models.Index(fields=['name', 'slug'], name='announcemen_name_e2683f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Місцезнаходження')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Підкатегорія')),
                ('deal_type', models.CharField(blank=True, max_length=50, verbose_name='Тип угоди')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement_images/', verbose_name='Зображення')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('status', models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Місцезнаходження',
                'verbose_name_plural': 'Місцезнаходження',
                'indexes': [models.Index(fields=['name', 'district'], name='announcemen_name_9127f1_idx')],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='announcements.announcement', verbose_name='Оголошення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='ID користувача')),
                ('username', models.CharField(max_length=100, verbose_name="Ім'я користувача")),
                ('question', models.TextField(verbose_name='Питання')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Відповідь')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('resolved', 'Вирішено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('handled_by_admin', models.BooleanField(default=False, verbose_name='Оброблено адміністратором')),
            ],
            options={
                'verbose_name': 'Запит на підтримку',
                'verbose_name_plural': 'Запити на підтримку',
                'indexes': [models.Index(fields=['user_id', 'status', 'created_at'], name='announcemen_user_id_b6cee7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.CreateModel(
            name='ApartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(blank=True, choices=[('Приватна особа', 'Приватна особа'), ('Бізнес', 'Бізнес')], max_length=50, verbose_name='Тип продавця')),
                ('building_type', models.CharField(blank=True, choices=[('Царський', 'Царський'), ('Сталінка', 'Сталінка'), ('Хрущовка', 'Хрущовка'), ('Чешка', 'Чешка'), ('Гостинка', 'Гостинка'), ('Гуртожиток', 'Гуртожиток')], max_length=50, verbose_name='Тип будинку')),
                ('residential_complex', models.CharField(blank=True, max_length=100, verbose_name='Назва ЖК')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Поверх')),
                ('total_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Загальна площа')),
                ('kitchen_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Площа кухні')),
                ('wall_type', models.CharField(blank=True, choices=[('Цегла', 'Цегла'), ('Панельний', 'Панельний'), ('Шпакоблочний', 'Шпакоблочний'), ('Газоблок', 'Газоблок'), ('СІП панель', 'СІП панель'), ('Інше', 'Інше')], max_length=50, verbose_name='Тип стін')),
                ('housing_type', models.CharField(blank=True, choices=[('Новобудова', 'Новобудова'), ('Вторинне', 'Вторинне')], max_length=50, verbose_name='Тип житла')),
                ('rooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10, verbose_name='Кількість кімнат')),
                ('layout', models.CharField(blank=True, choices=[('Студія', 'Студія'), ('Розділені', 'Розділені'), ('Суміжна,прохідна', 'Суміжна,прохідна'), ('Пентхаус', 'Пентхаус'), ('Багаторівнева', 'Багаторівнева'), ('Малосімейка', 'Малосімейка'), ('Смарт-квартира', 'Смарт-квартира'), ('Вільне планування', 'Вільне планування'), ('Двохстороння', 'Двохстороння')], max_length=50, verbose_name='Планування')),
                ('bathroom', models.CharField(blank=True, choices=[('Суміжний', 'Суміжний'), ('Розділений', 'Розділений'), ('2+', '2+')], max_length=50, verbose_name='Санвузол')),
                ('heating', models.CharField(blank=True, choices=[('Центральне', 'Центральне'), ('Індивідуальне', 'Індивідуальне'), ('Газове', 'Газове')], max_length=50, verbose_name='Опалення')),
                ('renovation', models.CharField(blank=True, choices=[('Євроремонт', 'Євроремонт'), ('Косметичний', 'Косметичний'), ('Без ремонту', 'Без ремонту'), ('Житловий стан', 'Житловий стан'), ('Авторський проект', 'Авторський проект')], max_length=50, verbose_name='Ремонт')),
                ('furnishing', models.CharField(blank=True, choices=[('Так', 'Так'), ('Ні', 'Ні')], max_length=10, verbose_name='Меблювання')),
                ('appliances', models.JSONField(blank=True, default=list, verbose_name='Побутова техніка')),
                ('multimedia', models.JSONField(blank=True, default=list, verbose_name='Мультимедіа')),
                ('comfort', models.JSONField(blank=True, default=list, verbose_name='Комфорт')),
                ('communications', models.JSONField(blank=True, default=list, verbose_name='Комунікації')),
                ('infrastructure', models.JSONField(blank=True, default=list, verbose_name='Інфраструктура')),
                ('landscape', models.JSONField(blank=True, default=list, verbose_name='Ландшафт')),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_details', to='announcements.announcement', verbose_name='Оголошення')),
            ],
            options={
                'verbose_name': 'Деталі квартири',
                'verbose_name_plural': 'Деталі квартир',
                'indexes': [models.Index(fields=['announcement'], name='announcemen_announc_e47ef2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category', 'subcategory', 'deal_type'], name='announcemen_categor_891ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='announcemen_owner_i_d74d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['announcement', 'user', 'created_at'], name='announcemen_announc_2f2405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='announcemen_user_id_2d273f_idx'),
        ),
    ]
