# Generated by Django 5.1.4 on 2025-05-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/', verbose_name='Зображення')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcements.announcement', verbose_name='Оголошення')),
            ],
            options={
                'verbose_name': 'Зображення оголошення',
                'verbose_name_plural': 'Зображення оголошень',
            },
        ),
    ]
