# Generated by Django 5.1.4 on 2025-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_image_announcementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images/', verbose_name='Зображення'),
        ),
        migrations.DeleteModel(
            name='AnnouncementImage',
        ),
    ]
