# Generated by Django 5.1.4 on 2025-04-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
