# Generated by Django 5.1.4 on 2025-05-05 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status'], name='announcemen_status_d67968_idx'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
