# Generated by Django 5.1.4 on 2025-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_order_announcement_remove_order_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Запит на підтримку',
                'verbose_name_plural': 'Запити на підтримку',
            },
        ),
    ]
