# Generated by Django 5.1.4 on 2025-04-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_delete_chat'),
        ('announcements', '0005_add_categories'),
    ]

    operations = [
    ]
