# Generated by Django 5.1.4 on 2025-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_merge_0004_delete_chat_0005_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deal_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип угоди'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Підкатегорія'),
        ),
    ]
